### ISSUE TITLE
What is "- verkant -"

### ISSUE THREAD

**Issue by DuncanLithgow** [NicklasOestergaard/BIM7AA#16]
There are 19 occurances of a Type Code Description "- verkant -" but no 'Beskrivelse / Synonymer/Eksempler' explaining of what this means. There is also no explanation in the change log from 3.2. There is also no explanation in the documentation or BDA.

What is the purpose of this item?

Suggestion: would it be an idea to add a description so the purpose is clear?

**Comment by tsolsen** [comment]
A spelling error. Should have been vakant. Will be corrected some time in the future.
https://ordnet.dk/ddo/ordbog?query=vakant

**Comment by DuncanLithgow** [comment]
jeg tænker det bare kunne hedder ledig ...
