### ISSUE TITLE
I cannot find a mapping file to other systems

### ISSUE THREAD

**Issue by DuncanLithgow** [NicklasOestergaard/BIM7AA#17]
For BIM7AATypeCodes 3.2 there was a great mapping table. This is of course not an exact science but it was very useful. I found it especially useful for learning the relevant CCS, IFC Classes and predefined types.

Are there plans for a new mapping table? Perhaps as a collaborative effort?

**Comment by tsolsen** [comment]
Thank you.

Some work has been done towards it https://github.com/bimtypecode/bimtypecode/tree/mapping-table-dk, but put on hold to focus on other releases. There are various talks around the subject with different stakeholders and collaborative efforts - either that will happen or this one will be completed.
MOLIO has in the mean time done a mapping between BIMTypeCode and CCI. Don't know where and when that is released.
